### ISSUE TITLE
Wrong linking for the CIS function

### ISSUE THREAD

**Issue by Djoop** [JuliaMath/VML.jl#15]
Hi, I am not sure to fully understand the naming conventions, but the actual code uses the input types to detect the function prefix (like _vmld, _vmlz). This works for most functions (that have the same input and output types), but not for `CIS`, which takes reals and returns complex numbers, but is defined as `_vmlcCIS` and `_vlczCIS`. I don't think we should use the output type instead, given that `Arg` (`angle`) does the opposite (complex->float, but also defined as `_vmlcArg` and `_vmlzArg`).
So I don't know what is the cleanest way to solve this case, but using a different prefix just for `CIS` does solve the problem. Sorry I'm not sure how to make a clean pull request as I already cloned the repo from the v0.7 PR, that has not been merged yet.

**Comment by Crown421** [comment]
I looked into this, unfortunately this is not consistent within VML, so it is not as easy as just picking the VML function based on output instead of input type. 
Happy to put your solution in.

**Comment by Crown421** [comment]
Pull request https://github.com/JuliaMath/VML.jl/pull/17 now contains CIS.

**Comment by aminya** [comment]
Closed by https://github.com/JuliaMath/VML.jl/pull/17
