### ISSUE TITLE
The tests are uncompleted and the README should be enriched

### ISSUE THREAD

**Issue by sunoru** [JuliaMath/VML.jl#5]
I'm trying to work on this.

I think it's necessary to tell the users that this package should only be used by the Julia language compiled by icc..

**Comment by simonbyrne** [comment]
It would be nice to have testing enabled on Travis for this. See https://github.com/travis-ci/travis-ci/issues/4604, and links therein.

**Comment by sunoru** [comment]
OK I'll try it

**Comment by sunoru** [comment]
Hum.. I only have an educational license for my Intel compilers, and isn't it not so good to use it in an open source program..?

**Comment by simonbyrne** [comment]
Yeah, I'm not sure that would fit within the terms of the license. It might be better to use one of the other options:
https://software.intel.com/en-us/free_tools_and_libraries

The open source license would appear promising, but this clause is probably too restrictive:

> You may install copies of the Materials on an unlimited number of computers provided that You are the only individual using the Materials and only one copy of the Materials is in use at any one time

The community license might work, but the links aren't working for me.

**Comment by sunoru** [comment]
I'm now using trial license every time. 
However after some time it shows "Installer checksum verification failed" again and again.. It seems to be a network problem..

**Comment by sunoru** [comment]
It probably works now~

**Comment by Crown421** [comment]
This issue is old, but it's content has been dealt with, even though further improvements are always possible.
